import { ActiveStatus } from '@/components/ActiveStatus';
import AuthContext from '@/context/AuthContext';
import ToasterContext from '@/context/ToasterContext';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<AuthContext>
					<div className='h-full'>{children}</div>
					<ToasterContext />
					<ActiveStatus />
				</AuthContext>
			</body>
		</html>
	);
}
